# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: Analyze with ShiftLeft NG SAST

on:
  schedule:
    - cron: "0 * * * *"  
  push: # include to analyze when you push
    branches:
      - master
      - feature/*
      - fix/*
  pull_request: # include to analyze when you create a pull request
    branches:
      - master

jobs:
  NG-SAST-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # We are building this application with Java 11
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        java-version: 11.0.x
    - name: Package with maven
      run: mvn compile package
    - name: Download ShiftLeft cli
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    # ShiftLeft requires Java 1.8. Post the package step override the version
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        java-version: 1.8
    - name: Analyze with NG SAST
      run: ${GITHUB_WORKSPACE}/sl analyze --app GH_Vulnado --tag branch=${GITHUB_REF} --java --cpg target/vulnado-0.0.1-SNAPSHOT.jar
      env:
        SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
    - name: json2htmltable
      uses: Siddhant-K-code/JSON-to-Table@v1
    - name: List Findings
      run: curl --location --request GET 'https://www.shiftleft.io/api/v4/orgs/947dc6c1-7af6-4a15-8469-dc9a0275e16f/apps/GH_Vulnado/findings' --header 'Authorization: Bearer eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDgxNTg1OTMsImlzcyI6IlNoaWZ0TGVmdCIsIm9yZ0lEIjoiOTQ3ZGM2YzEtN2FmNi00YTE1LTg0NjktZGM5YTAyNzVlMTZmIiwidXNlcklEIjoiYjE0YzQ4NDctZTllMy00MjIzLWFkOGItNTRkMmRmODNhMTg2Iiwic2NvcGVzIjpbInNlYXRzOndyaXRlIiwiZXh0ZW5kZWQiLCJhcGk6djIiLCJ1cGxvYWRzOndyaXRlIiwibG9nOndyaXRlIiwicGlwZWxpbmVzdGF0dXM6cmVhZCIsIm1ldHJpY3M6d3JpdGUiLCJwb2xpY2llczpjdXN0b21lciJdfQ.oDmeCh4usN0h5qY8zUjgSFkPhZjIIa75gv10ih98jKelsdlD8l8rkqtiFU7uTomK8ZSLjsScQrzEyJWg7zOO2jjyKnHJT_3td-bVhQY29cpTAucWjLK8Tl-5mscdLBLQCgJzH4Pt4NcveF92jwaAoPFIzNXCRbSpozYJtL4wfq6xI-f5wyspMHml-Z8x0fd8czKrdoH2JLs6zxDuUE-HPlQsEgj0wkYwDF7wtx_3ii8SxX9CfRML7QiwxjPdyF4lcSVnxIU8pzzDwVnp8hnudIgZFCekUh6204KdE_D8YPesbFe4fvAd-mw7XYhSQc7kOG4Lax_L6jBmhT_jhQHqWw'
    - name: Create status check
      run: |
        URL="https://www.shiftleft.io/violationlist/ShiftLeftJava?apps=ShiftLeftJava&isApp=1"
        GH_CHECK_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/check-runs"
        curl -XPOST $GH_CHECK_URL -H "Authorization: Token ${GITHUB_TOKEN}" -H "accept: application/vnd.github.antiope-preview+json" -H "Content-Type: application/json" -d "{\"name\": \"ShiftLeft NG SAST\", \"head_sha\": \"${GITHUB_REF}\", \"external_id\": \"ShiftLeftJava\", \"details_url\": \"${URL}\", \"status\": \"completed\", \"conclusion\": \"action_required\", \"output\": {\"title\": \"ShiftLeft NG SAST Findings\", \"summary\": \"Visit ${URL} for the findings\"}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
